# Generated by Django 5.2.11 on 2026-07-23 18:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHazardCode',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'historical hazard code',
                'verbose_name_plural': 'historical hazard codes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Permit Number')),
                ('description', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_excavation', models.BooleanField(default=False)),
                ('requires_loto', models.BooleanField(default=False)),
                ('is_confined_space', models.BooleanField(default=False)),
                ('is_equipment_test', models.BooleanField(default=False)),
                ('is_radiography', models.BooleanField(default=False)),
                ('is_diving', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_dept_approval', 'Dept. Approval'), ('pending_safety_review', 'Safety Review'), ('pending_permit_office', 'Permit Office Review'), ('isolation_required', 'Isolation Planning'), ('isolations_in_progress', 'Isolations In Progress'), ('ready_for_issue', 'Ready For Issue'), ('validated', 'Validated'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('authorized_issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_permits', to=settings.AUTH_USER_MODEL)),
                ('continuation_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuations', to='permits.permit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_permits', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='accounts.department')),
                ('hazard_codes', models.ManyToManyField(blank=True, related_name='permits', to='permits.hazardcode')),
                ('location_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='equipment.locationtag')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_permits', to=settings.AUTH_USER_MODEL)),
                ('permit_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_permits', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='permits_per_status_6c419b_idx'), models.Index(fields=['valid_from'], name='permits_per_valid_f_2652c1_idx'), models.Index(fields=['valid_to'], name='permits_per_valid_t_bd01ff_idx')],
            },
        ),
    ]
