# Generated by Django 5.2.11 on 2026-07-12 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_department'),
        ('equipment', '0020_alter_historicallocationtag_long_tag_and_more'),
        ('permits', '0001_initial'),
        ('work_orders', '0015_workordertask_is_main_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Permit Number')),
                ('description', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_excavation', models.BooleanField(default=False)),
                ('is_spading', models.BooleanField(default=False)),
                ('is_confined_space', models.BooleanField(default=False)),
                ('is_equipment_test', models.BooleanField(default=False)),
                ('is_radiography', models.BooleanField(default=False)),
                ('is_diving', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('issued', 'Issued'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('authorized_issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_permits', to=settings.AUTH_USER_MODEL)),
                ('continuation_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuations', to='permits.permit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_permits', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='accounts.department')),
                ('hazard_codes', models.ManyToManyField(blank=True, related_name='permits', to='permits.hazardcode')),
                ('location_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='equipment.locationtag')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_permits', to=settings.AUTH_USER_MODEL)),
                ('permit_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_permits', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='permits_per_status_6c419b_idx'), models.Index(fields=['valid_from'], name='permits_per_valid_f_2652c1_idx'), models.Index(fields=['valid_to'], name='permits_per_valid_t_bd01ff_idx')],
            },
        ),
    ]
