# Generated by Django 5.2.13 on 2026-08-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalapprovalrole',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalapprovalrole',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalapprovalrole',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='ApprovalRole',
        ),
        migrations.DeleteModel(
            name='HistoricalApprovalRole',
        ),
    ]
