# Generated by Django 5.2.11 on 2026-07-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_permit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permit',
            old_name='is_spading',
            new_name='requires_loto',
        ),
    ]
