# Generated by Django 5.2.13 on 2026-08-04 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_remove_historicalapprovalrole_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitapproval',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='permitapproval',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='permitapproval',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='permitapproval',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='permitapproval',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.DeleteModel(
            name='HistoricalPermitApproval',
        ),
    ]
