# Generated by Django 5.2.13 on 2026-08-05 06:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
        ('permits', '0003_remove_permitapproval_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitapprovalrolechoices',
            name='department_scope',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUIRED', 'Required')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpermitapprovalrolechoices',
            name='required_qualification',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.qualification'),
        ),
        migrations.AddField(
            model_name='historicalpermitapprovalrolechoices',
            name='unit_scope',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUIRED', 'Required')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='permitapprovalrolechoices',
            name='department_scope',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUIRED', 'Required')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='permitapprovalrolechoices',
            name='required_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_roles', to='accounts.qualification'),
        ),
        migrations.AddField(
            model_name='permitapprovalrolechoices',
            name='unit_scope',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUIRED', 'Required')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalPermitApprovalRoleAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('all_units', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('permit_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permittype')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permitapprovalrolechoices')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical permit approval role assignment',
                'verbose_name_plural': 'historical permit approval role assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PermitApprovalRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('all_units', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permit_role_assignments', to='accounts.department')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('permit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_role_assignments', to='permits.permittype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='permits.permitapprovalrolechoices')),
                ('units', models.ManyToManyField(blank=True, related_name='permit_role_assignments', to='equipment.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'permit_type', 'department'), name='uq_user_role_type_department')],
            },
        ),
    ]
