# Generated by Django 5.2.11 on 2026-08-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_historicalpermitapprovalrolechoices_department_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitworkflowstep',
            name='editable_roles',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permitapprovalrolechoices'),
        ),
        migrations.AddField(
            model_name='historicalpermitworkflowstep',
            name='is_editable_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permitworkflowstep',
            name='editable_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editable_workflow_steps', to='permits.permitapprovalrolechoices'),
        ),
        migrations.AddField(
            model_name='permitworkflowstep',
            name='is_editable_step',
            field=models.BooleanField(default=False),
        ),
    ]
