# Generated by Django 5.2.11 on 2026-08-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_historicalpermitworkflowstep_editable_roles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpermitworkflowstep',
            old_name='editable_roles',
            new_name='editable_role',
        ),
        migrations.RenameField(
            model_name='permitworkflowstep',
            old_name='editable_roles',
            new_name='editable_role',
        ),
    ]
