# Generated by Django 5.2.11 on 2026-08-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_rename_editable_roles_historicalpermitworkflowstep_editable_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permithazard',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='permitprecaution',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
