# Generated by Django 5.2.11 on 2026-08-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0007_alter_permithazard_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
