# Generated by Django 5.2.11 on 2026-08-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_alter_permit_valid_from_alter_permit_valid_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitWorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('SHIFT_1', 'Shift 1'), ('SHIFT_2', 'Shift 2')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_permit_work_shifts', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='permits.permit')),
            ],
            options={
                'ordering': ['date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='PermitShiftSignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_signoffs', to='permits.permitapprovalrolechoices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_shift_signoffs', to=settings.AUTH_USER_MODEL)),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='permits.permitworkshift')),
            ],
        ),
        migrations.AddConstraint(
            model_name='permitworkshift',
            constraint=models.UniqueConstraint(fields=('permit', 'date', 'shift'), name='uq_permit_work_shift'),
        ),
        migrations.AddConstraint(
            model_name='permitshiftsignoff',
            constraint=models.UniqueConstraint(fields=('work_shift', 'role'), name='uq_work_shift_role_signoff'),
        ),
    ]
