# Generated by Django 5.2.11 on 2026-08-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0009_permitworkshift_permitshiftsignoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitworkshift',
            name='work_leader',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
