# Generated by Django 5.2.11 on 2026-08-12 11:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_permitworkshift_work_leader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPermitTypeActiveShiftRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical permit type active shift role',
                'verbose_name_plural': 'historical permit type active shift roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PermitTypeActiveShiftRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='permitshiftsignoff',
            name='user',
        ),
        migrations.AddField(
            model_name='permitshiftsignoff',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permit_shift_signoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='permitshiftsignoff',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('signed_at__isnull', True), ('signed_by__isnull', True)), models.Q(('signed_at__isnull', False), ('signed_by__isnull', False)), _connector='OR'), name='shift_signoff_user_time_consistent'),
        ),
        migrations.AddField(
            model_name='historicalpermittypeactiveshiftrole',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registered By'),
        ),
        migrations.AddField(
            model_name='historicalpermittypeactiveshiftrole',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpermittypeactiveshiftrole',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='historicalpermittypeactiveshiftrole',
            name='permit_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permittype'),
        ),
        migrations.AddField(
            model_name='historicalpermittypeactiveshiftrole',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permitapprovalrolechoices'),
        ),
        migrations.AddField(
            model_name='permittypeactiveshiftrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registered By'),
        ),
        migrations.AddField(
            model_name='permittypeactiveshiftrole',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='permittypeactiveshiftrole',
            name='permit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_shift_roles', to='permits.permittype'),
        ),
        migrations.AddField(
            model_name='permittypeactiveshiftrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_type_active_shift_roles', to='permits.permitapprovalrolechoices'),
        ),
        migrations.AddConstraint(
            model_name='permittypeactiveshiftrole',
            constraint=models.UniqueConstraint(fields=('permit_type', 'role'), name='uq_permit_type_active_shift_role'),
        ),
    ]
