# Generated by Django 5.2.11 on 2026-08-12 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0011_historicalpermittypeactiveshiftrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitworkflowstep',
            name='code',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('active', 'Active'), ('closed', 'Closed')], help_text='Stable machine-readable identifier for this workflow step.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='permitworkflowstep',
            name='code',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('active', 'Active'), ('closed', 'Closed')], help_text='Stable machine-readable identifier for this workflow step.', max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='permitworkflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'code'), name='uq_workflow_step_code'),
        ),
    ]
