# Generated by Django 5.2.11 on 2026-08-12 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0012_historicalpermitworkflowstep_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permitworkflowstep',
            name='uq_workflow_step_code',
        ),
        migrations.RenameField(
            model_name='historicalpermitworkflowstep',
            old_name='code',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='permitworkflowstep',
            old_name='code',
            new_name='state',
        ),
        migrations.AddIndex(
            model_name='permitworkflowstep',
            index=models.Index(fields=['workflow', 'state'], name='workflow_step_state_idx'),
        ),
    ]
