# Generated by Django 5.2.11 on 2026-08-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0013_remove_permitworkflowstep_uq_workflow_step_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitshiftsignoff',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permitshiftsignoff',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
