# Generated by Django 5.2.11 on 2026-08-13 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0014_permitshiftsignoff_is_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permitworkshift',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permitworkshift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_permit_work_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permitworkshift',
            name='status',
            # Existing rows predate the release lifecycle, so preserve them
            # as historical/closed rows.  New model instances default to open.
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='closed', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='permitworkshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('permit',), name='uq_one_open_work_shift_per_permit'),
        ),
    ]
