# Generated by Django 5.2.11 on 2026-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0015_permitworkshift_closed_at_permitworkshift_closed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitworkshift',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10),
        ),
    ]
