# Generated by Django 5.2.11 on 2026-08-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0016_alter_permitworkshift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitworkshift',
            name='worker_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of workers planned to work during this shift.', null=True, verbose_name='Number of workers'),
        ),
    ]
