# Generated by Django 5.2.11 on 2026-08-16 12:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0017_permitworkshift_worker_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPermitCloseoutItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permitapprovalrolechoices')),
            ],
            options={
                'verbose_name': 'historical Permit Close-out Item',
                'verbose_name_plural': 'historical Permit Close-out Items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PermitCloseoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closeout_items', to='permits.permitapprovalrolechoices')),
            ],
            options={
                'verbose_name': 'Permit Close-out Item',
                'verbose_name_plural': 'Permit Close-out Items',
                'ordering': ['display_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitCloseoutSignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closeout_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_signoffs', to='permits.permitcloseoutitem')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_permit_closeout_signoffs', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeout_signoffs', to='permits.permit')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permit_closeout_signoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permit Close-out Sign-off',
                'verbose_name_plural': 'Permit Close-out Sign-offs',
                'ordering': ['closeout_item__display_order', 'closeout_item__code', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='permit',
            name='closeout_items',
            field=models.ManyToManyField(blank=True, related_name='permits', through='permits.PermitCloseoutSignoff', to='permits.permitcloseoutitem'),
        ),
        migrations.AddConstraint(
            model_name='permitcloseoutsignoff',
            constraint=models.UniqueConstraint(fields=('permit', 'closeout_item'), name='unique_permit_closeout_item'),
        ),
        migrations.AddConstraint(
            model_name='permitcloseoutsignoff',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('signed_at__isnull', True), ('signed_by__isnull', True)), models.Q(('signed_at__isnull', False), ('signed_by__isnull', False)), _connector='OR'), name='permit_closeout_signer_timestamp_ck'),
        ),
    ]
