# Generated by Django 5.2.11 on 2026-08-18 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0019_historicalshiftschedule_shiftschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shiftschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('shift',), name='unique_active_shift_schedule_per_shift'),
        ),
    ]
