# Generated by Django 5.2.11 on 2026-08-18 17:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_shiftschedule_unique_active_shift_schedule_per_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FireGasESD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Fire, Gas & ESD',
                'verbose_name_plural': 'Fire, Gas & ESDs',
                'ordering': ['display_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFireGasESD',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registration Date')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'historical Fire, Gas & ESD',
                'verbose_name_plural': 'historical Fire, Gas & ESDs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PermitFireGasESD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_zone', models.CharField(help_text='Unit, area, or zone where this Fire/Gas/ESD isolation applies.', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('isolated_time', models.DateTimeField(blank=True, help_text='The actual time the isolation was performed.', null=True)),
                ('isolated_confirmed_at', models.DateTimeField(blank=True, help_text='The time the isolation confirmation was recorded.', null=True)),
                ('deisolated_time', models.DateTimeField(blank=True, help_text='The actual time the de-isolation was performed.', null=True)),
                ('deisolated_confirmed_at', models.DateTimeField(blank=True, help_text='The time the de-isolation confirmation was recorded.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_permit_fire_gas_esd_items', to=settings.AUTH_USER_MODEL)),
                ('deisolated_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_fg_esd_deisolations', to=settings.AUTH_USER_MODEL)),
                ('fire_gas_esd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_links', to='permits.firegasesd')),
                ('isolated_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_fg_esd_isolations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_permit_fire_gas_esd_items', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_fire_gas_esd_items', to='permits.permit')),
            ],
            options={
                'verbose_name': 'Permit Fire, Gas & ESD Item',
                'verbose_name_plural': 'Permit Fire, Gas & ESD Items',
                'ordering': ['permit', 'fire_gas_esd', 'unit_zone', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='permit',
            name='fire_gas_esd_items',
            field=models.ManyToManyField(blank=True, related_name='permits', through='permits.PermitFireGasESD', to='permits.firegasesd'),
        ),
        migrations.AddConstraint(
            model_name='permitfiregasesd',
            constraint=models.UniqueConstraint(fields=('permit', 'fire_gas_esd', 'unit_zone'), name='permit_fg_esd_unique_per_zone'),
        ),
        migrations.AddConstraint(
            model_name='permitfiregasesd',
            constraint=models.CheckConstraint(condition=models.Q(('isolated_confirmed_at__isnull', True), ('isolated_time__isnull', False), _connector='OR'), name='permit_fg_esd_isolated_confirm_requires_time_ck'),
        ),
        migrations.AddConstraint(
            model_name='permitfiregasesd',
            constraint=models.CheckConstraint(condition=models.Q(('deisolated_confirmed_at__isnull', True), ('deisolated_time__isnull', False), _connector='OR'), name='permit_fg_esd_deisolated_confirm_requires_time_ck'),
        ),
    ]
