# Generated by Django 5.2.11 on 2026-08-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0021_firegasesd_historicalfiregasesd_permitfiregasesd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firegasesd',
            name='role',
            field=models.ForeignKey(help_text='The role authorized to perform and confirm this type of isolation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fire_gas_isolations', to='permits.permitapprovalrolechoices'),
        ),
        migrations.AddField(
            model_name='historicalfiregasesd',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The role authorized to perform and confirm this type of isolation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permits.permitapprovalrolechoices'),
        ),
    ]
