# Generated by Django 5.2.11 on 2026-08-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0022_firegasesd_role_historicalfiregasesd_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firegasesd',
            name='role',
            field=models.ForeignKey(help_text='The role authorized to perform and confirm this type of isolation.', on_delete=django.db.models.deletion.PROTECT, related_name='fire_gas_isolations', to='permits.permitapprovalrolechoices'),
        ),
    ]
