# Generated by Django 5.2.13 on 2026-08-29 13:36

import django.db.models.deletion
import django.utils.timezone
import permits.models.permit_attachment_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0023_alter_firegasesd_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(help_text='Maximum size: 25 MB.', upload_to=permits.models.permit_attachment_models.permit_attachment_upload_to, validators=[permits.models.permit_attachment_models.validate_attachment_size])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_attachments_modified', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='permits.permit')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permit Attachment',
                'verbose_name_plural': 'Permit Attachments',
                'ordering': ['-uploaded_at', '-pk'],
                'indexes': [models.Index(fields=['permit', '-uploaded_at'], name='permit_att_permit_date_idx'), models.Index(fields=['uploaded_by', '-uploaded_at'], name='permit_att_uploader_date_idx')],
            },
        ),
    ]
