# Generated by Django 5.2.13 on 2026-09-01 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
        ('permits', '0024_permitattachment'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('safety_type', models.CharField(choices=[('ISOLATION', 'Isolation'), ('CONFINED_SPACE', 'Confined Space'), ('DIVING', 'Diving'), ('EXCAVATION', 'Excavation'), ('EQUIPMENT_TEST', 'Equipment Test'), ('RADIOGRAPHY', 'Radiography')], db_index=True, max_length=30)),
                ('scope_of_work', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('ALLOWED', 'Allowed'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('allowed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_safety_permits', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_permits_at_step', to='permits.permitworkflowstep')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_permits', to='accounts.department')),
                ('location_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_permits', to='equipment.locationtag')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_safety_permits', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_permits', to='work_orders.workorder')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_permits', to='permits.permitworkflow')),
            ],
            options={
                'verbose_name': 'Safety Permit',
                'verbose_name_plural': 'Safety Permits',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ConfinedSpacePermit',
            fields=[
                ('safetypermit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.safetypermit')),
            ],
            options={
                'verbose_name': 'Confined Space Safety Permit',
                'verbose_name_plural': 'Confined Space Safety Permits',
            },
            bases=('permits.safetypermit',),
        ),
        migrations.CreateModel(
            name='DivingPermit',
            fields=[
                ('safetypermit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.safetypermit')),
            ],
            options={
                'verbose_name': 'Diving Safety Permit',
                'verbose_name_plural': 'Diving Safety Permits',
            },
            bases=('permits.safetypermit',),
        ),
        migrations.CreateModel(
            name='EquipmentTestPermit',
            fields=[
                ('safetypermit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.safetypermit')),
            ],
            options={
                'verbose_name': 'Equipment Test Safety Permit',
                'verbose_name_plural': 'Equipment Test Safety Permits',
            },
            bases=('permits.safetypermit',),
        ),
        migrations.CreateModel(
            name='ExcavationPermit',
            fields=[
                ('safetypermit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.safetypermit')),
            ],
            options={
                'verbose_name': 'Excavation Safety Permit',
                'verbose_name_plural': 'Excavation Safety Permits',
            },
            bases=('permits.safetypermit',),
        ),
        migrations.CreateModel(
            name='IsolationPermit',
            fields=[
                ('safetypermit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.safetypermit')),
            ],
            options={
                'verbose_name': 'Isolation Safety Permit',
                'verbose_name_plural': 'Isolation Safety Permits',
            },
            bases=('permits.safetypermit',),
        ),
        migrations.CreateModel(
            name='RadiographyPermit',
            fields=[
                ('safetypermit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.safetypermit')),
            ],
            options={
                'verbose_name': 'Radiography Safety Permit',
                'verbose_name_plural': 'Radiography Safety Permits',
            },
            bases=('permits.safetypermit',),
        ),
        migrations.CreateModel(
            name='PermitSafetyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_status', models.CharField(choices=[('ALLOWED', 'Allowed'), ('ACTIVE', 'Active')], default='ALLOWED', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_permit_safety_requirements', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_requirements', to='permits.permit')),
                ('safety_permit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_permit_requirements', to='permits.safetypermit')),
            ],
            options={
                'verbose_name': 'Permit Safety Requirement',
                'verbose_name_plural': 'Permit Safety Requirements',
                'ordering': ['permit', 'safety_permit', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='permit',
            name='required_safety_permits',
            field=models.ManyToManyField(blank=True, related_name='required_by_permits', through='permits.PermitSafetyRequirement', to='permits.safetypermit'),
        ),
        migrations.AddIndex(
            model_name='safetypermit',
            index=models.Index(fields=['safety_type', 'status'], name='safety_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='safetypermit',
            index=models.Index(fields=['location_tag', 'status'], name='safety_loc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='safetypermit',
            index=models.Index(fields=['work_order', 'status'], name='safety_wo_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='safetypermit',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='safety_permit_valid_window_ck'),
        ),
        migrations.AddConstraint(
            model_name='permitsafetyrequirement',
            constraint=models.UniqueConstraint(fields=('permit', 'safety_permit'), name='uq_permit_safety_requirement'),
        ),
        migrations.AddConstraint(
            model_name='permitsafetyrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='permit_safety_req_valid_window_ck'),
        ),
    ]
