# Generated by Django 5.2.13 on 2026-09-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0025_safetypermit_confinedspacepermit_divingpermit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetypermit',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='safetypermit',
            name='allowed_at',
        ),
        migrations.RemoveField(
            model_name='safetypermit',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='safetypermit',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='safetypermit',
            name='suspended_at',
        ),
    ]
