# Generated by Django 5.2.11 on 2026-09-10 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0030_hardcode_paper_safety_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpapersafetypermittype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Paper Safety Permit Type', 'verbose_name_plural': 'historical Paper Safety Permit Types'},
        ),
        migrations.AlterModelOptions(
            name='historicalpapersafetypermitworkflowstep',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Paper Safety Permit Workflow Step', 'verbose_name_plural': 'historical Paper Safety Permit Workflow Steps'},
        ),
        migrations.AlterModelOptions(
            name='papersafetypermittype',
            options={'ordering': ['sort_order', 'name', 'pk'], 'verbose_name': 'Paper Safety Permit Type', 'verbose_name_plural': 'Paper Safety Permit Types'},
        ),
        migrations.AlterModelOptions(
            name='papersafetypermitworkflowstep',
            options={'ordering': ['step_order', 'pk'], 'verbose_name': 'Paper Safety Permit Workflow Step', 'verbose_name_plural': 'Paper Safety Permit Workflow Steps'},
        ),
        migrations.AlterField(
            model_name='historicalpapersafetypermittype',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalpapersafetypermitworkflowstep',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='papersafetypermittype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registered By'),
        ),
        migrations.AlterField(
            model_name='papersafetypermittype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='papersafetypermitworkflowstep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registered By'),
        ),
        migrations.AlterField(
            model_name='papersafetypermitworkflowstep',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
    ]
