# Generated by Django 5.2.11 on 2026-09-10 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0031_alter_historicalpapersafetypermittype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RemoveConstraint(
                    model_name='permitpapersafetypermit',
                    name='paper_safety_active_complete_ck',
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='permitpapersafetypermit',
                    name='paper_safety_active_complete_ck',
                ),
                migrations.RemoveConstraint(
                    model_name='permitpapersafetypermit',
                    name='paper_safety_active_complete_ck',
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name='permitpapersafetypermit',
            name='paper_safety_permit_status_idx',
        ),
        migrations.RemoveField(
            model_name='permitpapersafetypermit',
            name='status',
        ),
        migrations.AlterField(
            model_name='permitpapersafetypermit',
            name='current_step',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='paper_safety_permits', to='permits.papersafetypermitworkflowstep'),
        ),
        migrations.AddIndex(
            model_name='permitpapersafetypermit',
            index=models.Index(fields=['permit', 'current_step'], name='paper_safety_permit_step_idx'),
        ),
    ]
