# Generated by Django 5.2.11 on 2026-09-11 08:57

import re

from django.db import migrations, models


STEP_BLOCKING = {
    "Pending": True,
    "Cancelled": False,
    "Activated": False,
    "Expired": True,
    # Terminated was DEACTIVE and therefore blocked under the previous
    # all-safety-permits-must-be-ACTIVE rule.
    "Terminated": True,
}

LEGACY_STEP_NAMES = {
    "PENDING": "Pending",
    "CANCELLED": "Cancelled",
    "ACTIVE": "Activated",
    "ACTIVATED": "Activated",
    "EXPIRED": "Expired",
    "TERMINATED": "Terminated",
}
TRANSITION_RE = re.compile(r"^Step changed from (.+?) to (.+?)\.")


def configure_step_blocking(apps, schema_editor):
    Step = apps.get_model("permits", "PaperSafetyPermitWorkflowStep")
    HistoricalStep = apps.get_model(
        "permits", "HistoricalPaperSafetyPermitWorkflowStep"
    )
    StatusHistory = apps.get_model(
        "permits", "PermitPaperSafetyPermitStatusHistory"
    )

    # Preserve custom-step behaviour: ACTIVE was non-blocking and DEACTIVE
    # was blocking. Then apply the explicit business rules for built-in steps.
    Step.objects.filter(status="ACTIVE").update(blocks_main_permit=False)
    HistoricalStep.objects.filter(status="ACTIVE").update(
        blocks_main_permit=False
    )
    for name, blocks_main_permit in STEP_BLOCKING.items():
        Step.objects.filter(name=name).update(
            blocks_main_permit=blocks_main_permit
        )
        HistoricalStep.objects.filter(name=name).update(
            blocks_main_permit=blocks_main_permit
        )

    # Transition remarks contain the exact old/new step names. Use them where
    # available, then normalize older enum values so ACTIVE/DEACTIVE no longer
    # appear in the workflow audit UI.
    for event in StatusHistory.objects.all().iterator():
        from_step = None
        to_step = None
        match = TRANSITION_RE.match(event.remarks or "")
        if match:
            from_step, to_step = match.groups()

        event.from_status = (
            from_step
            or LEGACY_STEP_NAMES.get(event.from_status, event.from_status)
        )
        event.to_status = (
            to_step
            or LEGACY_STEP_NAMES.get(event.to_status, event.to_status)
        )
        if event.from_status == "DEACTIVE":
            event.from_status = "Pending"
        if event.to_status == "DEACTIVE":
            event.to_status = "Pending"
        event.save(update_fields=["from_status", "to_status"])


def restore_legacy_values(apps, schema_editor):
    Step = apps.get_model("permits", "PaperSafetyPermitWorkflowStep")
    HistoricalStep = apps.get_model(
        "permits", "HistoricalPaperSafetyPermitWorkflowStep"
    )
    StatusHistory = apps.get_model(
        "permits", "PermitPaperSafetyPermitStatusHistory"
    )

    for model in (Step, HistoricalStep):
        model.objects.filter(blocks_main_permit=False).update(status="ACTIVE")
        model.objects.filter(blocks_main_permit=True).update(status="DEACTIVE")

    StatusHistory.objects.filter(from_status="Activated").update(
        from_status="ACTIVE"
    )
    StatusHistory.objects.filter(to_status="Activated").update(
        to_status="ACTIVE"
    )
    StatusHistory.objects.exclude(from_status__in=["", "ACTIVE"]).update(
        from_status="DEACTIVE"
    )
    StatusHistory.objects.exclude(to_status="ACTIVE").update(
        to_status="DEACTIVE"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0032_remove_permitpapersafetypermit_paper_safety_active_complete_ck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpapersafetypermitworkflowstep",
            name="blocks_main_permit",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether a safety permit at this step prevents the main "
                    "permit from proceeding."
                ),
            ),
        ),
        migrations.AddField(
            model_name="papersafetypermitworkflowstep",
            name="blocks_main_permit",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether a safety permit at this step prevents the main "
                    "permit from proceeding."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="permitpapersafetypermitstatushistory",
            name="from_status",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="permitpapersafetypermitstatushistory",
            name="to_status",
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(configure_step_blocking, restore_legacy_values),
        migrations.RemoveField(
            model_name="historicalpapersafetypermitworkflowstep",
            name="status",
        ),
        migrations.RemoveField(
            model_name="papersafetypermitworkflowstep",
            name="status",
        ),
    ]
