# Generated by Django 5.2.11 on 2026-09-11 11:10

from django.db import migrations


def clean_generated_remarks(apps, schema_editor):
    StatusHistory = apps.get_model(
        "permits", "PermitPaperSafetyPermitStatusHistory"
    )

    for event in StatusHistory.objects.exclude(remarks="").iterator():
        remarks = (event.remarks or "").strip()
        if remarks == "Created paper safety permit.":
            cleaned_remarks = ""
        else:
            generated_prefix = (
                f"Step changed from {event.from_status} "
                f"to {event.to_status}."
            )
            cleaned_remarks = remarks
            if remarks.startswith(generated_prefix):
                cleaned_remarks = remarks[len(generated_prefix):].strip()

        if cleaned_remarks != event.remarks:
            event.remarks = cleaned_remarks
            event.save(update_fields=["remarks"])


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0033_refactor_paper_safety_step_blocking"),
    ]

    operations = [
        migrations.RunPython(clean_generated_remarks, migrations.RunPython.noop),
    ]
