# Generated by Django 5.2.11 on 2026-09-11 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0034_clean_paper_safety_generated_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpapersafetypermittype',
            name='validity_shifts',
            field=models.PositiveIntegerField(default=1, help_text='Number of work shifts this safety permit remains active after approval.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Active shifts'),
        ),
        migrations.AddField(
            model_name='papersafetypermittype',
            name='validity_shifts',
            field=models.PositiveIntegerField(default=1, help_text='Number of work shifts this safety permit remains active after approval.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Active shifts'),
        ),
    ]
