# Generated by Django 5.2.11 on 2026-05-20 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_department'),
        ('equipment', '0017_alter_equipment_serial_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('wo_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='WO Number')),
                ('actual_start', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('waiting', 'Waiting')], db_index=True, default='ongoing', max_length=20)),
                ('employees', models.TextField(blank=True, help_text='Names of workers separated by comma.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='accounts.department')),
                ('father_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_reports', to='equipment.locationtag')),
                ('location_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='equipment.locationtag')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-date'],
            },
        ),
    ]
