# Generated by Django 5.2.11 on 2026-05-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0002_alter_dailyreport_actual_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
