# Generated by Django 5.2.11 on 2026-05-20 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_department'),
        ('daily_reports', '0003_alter_dailyreport_modified_at'),
        ('equipment', '0017_alter_equipment_serial_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['location_tag', 'date'], name='idx_loc_date'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['department', 'date'], name='idx_dept_date'),
        ),
    ]
