# Generated by Django 5.2.11 on 2026-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0004_dailyreport_idx_loc_date_dailyreport_idx_dept_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('waiting', 'Waiting')], db_index=True, max_length=20),
        ),
    ]
