# Generated by Django 5.2.11 on 2026-03-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='documents',
        ),
    ]
