# Generated by Django 5.2.11 on 2026-03-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtag',
            name='obj_criticality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_locations', to='equipment.objectcriticality'),
        ),
    ]
