# Generated by Django 5.2.11 on 2026-03-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_historicallocationtag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unit', 'verbose_name_plural': 'historical Units'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_code'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
