# Generated by Django 5.2.11 on 2026-03-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_historicalunit_options_alter_unit_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallocationtag',
            old_name='operational_unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='locationtag',
            old_name='operational_unit',
            new_name='unit',
        ),
    ]
