# Generated by Django 5.2.11 on 2026-04-24 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_rename_operational_unit_historicallocationtag_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdocument',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalequipmentdocument',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='loc_tag',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='LocationTagChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved with change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('loc_tag', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('long_tag', models.CharField(blank=True, max_length=250, null=True)),
                ('train', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('mih_level', models.CharField(blank=True, max_length=150, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('location_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='equipment.locationtag')),
                ('obj_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_locations_requests', to='equipment.objectcategory')),
                ('obj_criticality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_locations_requests', to='equipment.objectcriticality')),
                ('obj_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_locations_requests', to='equipment.objecttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_location_tags', to='equipment.locationtag')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_locations_requests', to='equipment.unit')),
            ],
            options={
                'verbose_name': 'Location Tag Change Request',
                'verbose_name_plural': 'Location Tags Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
