# Generated by Django 5.2.11 on 2026-04-24 11:39

import django.db.models.deletion
import equipment.models.equipment_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipmentdocument_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved with change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='equipment.equipment')),
                ('functional_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_location_requests', to='equipment.locationtag')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Change Request',
                'verbose_name_plural': 'Equipment Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDocumentChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved with change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=equipment.models.equipment_models.get_document_upload_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='equipment.equipmentdocument')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='equipment.equipment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Document Change Request',
                'verbose_name_plural': 'Equipment Document Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
