# Generated by Django 5.2.11 on 2026-04-24 11:42

import django.db.models.deletion
import equipment.models.equipment_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipmentchangerequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentchangerequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='equipmentdocumentchangerequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='locationtagchangerequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='equipment.equipment', verbose_name='Target Equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='functional_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_change_requests', to='equipment.locationtag', verbose_name='Functional Location'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Requested At'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_with_change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='equipment.equipmentdocument', verbose_name='Target Document'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_change_requests', to='equipment.equipment', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=equipment.models.equipment_models.get_document_upload_path, verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Requested At'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_with_change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='loc_tag',
            field=models.CharField(max_length=50, verbose_name='Location Tag Code'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='location_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='equipment.locationtag', verbose_name='Target Location Tag'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='long_tag',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Long Tag'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='mih_level',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='MIH Level'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='obj_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_tag_change_requests', to='equipment.objectcategory'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='obj_criticality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_tag_change_requests', to='equipment.objectcriticality'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='obj_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_tag_change_requests', to='equipment.objecttype'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_location_tag_requests', to='equipment.locationtag', verbose_name='Parent Location Tag'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Requested At'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_with_change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_tag_change_requests', to='equipment.unit'),
        ),
    ]
