# Generated by Django 5.2.11 on 2026-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipmentchangerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtagchangerequest',
            name='changes',
            field=models.JSONField(default=dict),
        ),
    ]
