# Generated by Django 5.2.11 on 2026-04-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_locationtagchangerequest_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('remove', 'Remove')], max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('remove', 'Remove')], max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('remove', 'Remove')], max_length=20, verbose_name='Action Type'),
        ),
    ]
