# Generated by Django 5.2.11 on 2026-05-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_equipmentchangerequest_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentchangerequest',
            name='changes',
            field=models.JSONField(default=dict),
        ),
    ]
