# Generated by Django 5.2.11 on 2026-05-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_equipmentchangerequest_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentdocumentchangerequest',
            options={'ordering': ['change_request__id', 'id'], 'verbose_name': 'Equipment Document Change', 'verbose_name_plural': 'Equipment Document Changes'},
        ),
        migrations.RemoveField(
            model_name='equipmentdocumentchangerequest',
            name='action',
        ),
        migrations.RemoveField(
            model_name='equipmentdocumentchangerequest',
            name='document',
        ),
        migrations.RemoveField(
            model_name='equipmentdocumentchangerequest',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentdocumentchangerequest',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='equipmentdocumentchangerequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='equipmentdocumentchangerequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='equipmentdocumentchangerequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='equipmentdocumentchangerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='equipmentdocumentchangerequest',
            name='change_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='equipment.equipmentchangerequest'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='file',
            field=models.FileField(upload_to='equipment_request_documents/'),
        ),
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
