# Generated by Django 5.2.11 on 2026-05-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_alter_equipmentdocumentchangerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdocumentchangerequest',
            name='change_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='equipment.equipmentchangerequest'),
        ),
    ]
