# Generated by Django 5.2.13 on 2026-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_alter_equipmentdocumentchangerequest_change_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved_with_change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved_with_change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, verbose_name='Status'),
        ),
    ]
