# Generated by Django 5.2.13 on 2026-05-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_alter_equipmentchangerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentchangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved_with_change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='locationtagchangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved_with_change', 'Approved with Change'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
