# Generated by Django 5.2.13 on 2026-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_alter_equipmentchangerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number'),
        ),
    ]
