# Generated by Django 5.2.11 on 2026-05-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_alter_equipment_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocationtag',
            name='pattern',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='locationtag',
            name='pattern',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
