# Generated by Django 5.2.11 on 2026-05-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_historicallocationtag_pattern_locationtag_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocationtag',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='locationtag',
            name='pattern',
        ),
    ]
