# Generated by Django 5.2.11 on 2026-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_remove_historicallocationtag_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocationtag',
            name='long_tag',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='long_tag',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
