# Generated by Django 5.2.11 on 2026-06-01 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_department'),
        ('equipment', '0020_alter_historicallocationtag_long_tag_and_more'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('short_text', models.CharField(max_length=255)),
                ('long_text', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_breakdown', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted to Work Order')], db_index=True, default='SUBMITTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fault_reports', to='equipment.equipment')),
                ('location_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fault_reports', to='equipment.locationtag')),
                ('planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fault_reports_planner', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='work_orders.priority')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_reports_reported', to=settings.AUTH_USER_MODEL)),
                ('reported_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_reports_dep', to='accounts.department')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='work_orders.symptom')),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['status'], name='work_orders_status_207771_idx'), models.Index(fields=['reported_at'], name='work_orders_reporte_c1cea3_idx'), models.Index(fields=['location_tag'], name='work_orders_locatio_4ddfed_idx'), models.Index(fields=['equipment'], name='work_orders_equipme_e49c6c_idx'), models.Index(fields=['planner'], name='work_orders_planner_d93904_idx')],
            },
        ),
    ]
