# Generated by Django 5.2.11 on 2026-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_faultreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='report_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('code', 'year')},
            },
        ),
    ]
