# Generated by Django 5.2.11 on 2026-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_alter_faultreport_report_number_documentsequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faultreport',
            old_name='short_text',
            new_name='directive',
        ),
        migrations.RemoveField(
            model_name='faultreport',
            name='long_text',
        ),
        migrations.AddField(
            model_name='faultreport',
            name='fault_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
