# Generated by Django 5.2.11 on 2026-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_rename_short_text_faultreport_directive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='fault_desc',
            field=models.TextField(),
        ),
    ]
