# Generated by Django 5.2.11 on 2026-06-01 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0005_alter_faultreport_fault_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='faultreport',
            name='work_orders_status_207771_idx',
        ),
        migrations.RemoveIndex(
            model_name='faultreport',
            name='work_orders_reporte_c1cea3_idx',
        ),
        migrations.RemoveIndex(
            model_name='faultreport',
            name='work_orders_locatio_4ddfed_idx',
        ),
        migrations.RemoveIndex(
            model_name='faultreport',
            name='work_orders_equipme_e49c6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='faultreport',
            name='work_orders_planner_d93904_idx',
        ),
        migrations.RenameField(
            model_name='faultreport',
            old_name='approved_at',
            new_name='planner_reviewed_at',
        ),
        migrations.RenameField(
            model_name='faultreport',
            old_name='approval_comment',
            new_name='review_comment',
        ),
        migrations.RenameField(
            model_name='faultreport',
            old_name='converted_at',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='faultreport',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='faultreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Work Order')], db_index=True, default='SUBMITTED', max_length=20),
        ),
    ]
