# Generated by Django 5.2.13 on 2026-06-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_department'),
        ('work_orders', '0006_remove_faultreport_work_orders_status_207771_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultreport',
            name='is_breakdown',
        ),
        migrations.AddField(
            model_name='faultreport',
            name='executing_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fault_executing_dep', to='accounts.department'),
            preserve_default=False,
        ),
    ]
