# Generated by Django 5.2.13 on 2026-06-11 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0007_remove_faultreport_is_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='project_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='work_orders.projectcode'),
        ),
    ]
