# Generated by Django 5.2.13 on 2026-06-11 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0009_detectionmethod_historicaldetectionmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='detection_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='work_orders.detectionmethod'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='parent_work_order_number',
            field=models.CharField(blank=True, help_text='Optional parent work order reference number.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='work_orders.worktype'),
        ),
    ]
