# Generated by Django 5.2.11 on 2026-06-25 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_department'),
        ('equipment', '0020_alter_historicallocationtag_long_tag_and_more'),
        ('work_orders', '0010_faultreport_detection_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('directive', models.CharField(max_length=255)),
                ('fault_desc', models.TextField()),
                ('cause_description', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PLANNED', 'Planned'), ('IN_EXECUTION', 'In Execution'), ('WORK_DONE', 'Work Done'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='work_orders.cause')),
                ('detection_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='work_orders.detectionmethod')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.equipment')),
                ('fault_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='work_orders.faultreport')),
                ('location_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.locationtag')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_modifier', to=settings.AUTH_USER_MODEL)),
                ('parent_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_work_orders', to='work_orders.workorder')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='work_orders.priority')),
                ('project_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='work_orders.projectcode')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_reported', to=settings.AUTH_USER_MODEL)),
                ('reported_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_rep_dep', to='accounts.department')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='work_orders.symptom')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='work_orders.worktype')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField(blank=True)),
                ('directive', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ESTIMATED', 'Estimated'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=30)),
                ('work_done_description', models.TextField(blank=True, null=True)),
                ('permit', models.CharField(blank=True, max_length=20, null=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_finish', models.DateField(blank=True, null=True)),
                ('waiting_history', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_finish', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_itam', models.TextField(blank=True, null=True)),
                ('awaiting_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_orders.awaitingreason')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_tasks', to=settings.AUTH_USER_MODEL)),
                ('performed_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='work_orders.performedaction')),
                ('planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_tasks', to=settings.AUTH_USER_MODEL)),
                ('task_executing_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executing_tasks', to='accounts.department')),
                ('task_requester_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tasks', to='accounts.department')),
                ('work_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_tasks', to=settings.AUTH_USER_MODEL)),
                ('work_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mastered_tasks', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['work_order', 'task_number'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='work_orders_status_c63f41_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['reported_at'], name='work_orders_reporte_f0ea1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='workordertask',
            constraint=models.UniqueConstraint(fields=('work_order', 'task_number'), name='unique_task_per_wo'),
        ),
    ]
