# Generated by Django 5.2.11 on 2026-06-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0011_workorder_workordertask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='fault_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='work_orders.faultreport'),
        ),
    ]
