# Generated by Django 5.2.11 on 2026-06-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0013_alter_workorder_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='wo_number_numeric',
            field=models.PositiveIntegerField(db_index=True, default=2600001, unique=True),
            preserve_default=False,
        ),
    ]
