# Generated by Django 5.2.13 on 2026-07-02 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_department'),
        ('work_orders', '0014_workorder_wo_number_numeric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='is_main_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['task_requester_department'], name='work_orders_task_re_dfde66_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['task_executing_department'], name='work_orders_task_ex_f74dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['performed_action'], name='work_orders_perform_790c46_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['awaiting_reason'], name='work_orders_awaitin_0ffa2f_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['planned_start'], name='work_orders_planned_b864f0_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['planned_finish'], name='work_orders_planned_9ee06f_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['actual_start'], name='work_orders_actual__d71562_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['actual_finish'], name='work_orders_actual__01e1af_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['permit'], name='work_orders_permit_e88ae4_idx'),
        ),
    ]
