# Generated by Django 5.2.11 on 2026-07-16 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilterFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=50)),
                ('view_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('sort_by', models.CharField(blank=True, default='', max_length=100)),
                ('per_page', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'app_key', 'view_key', 'name'],
                'indexes': [models.Index(fields=['user', 'app_key', 'view_key'], name='accounts_us_user_id_3ab183_idx'), models.Index(fields=['user', 'app_key', 'view_key', 'is_default'], name='accounts_us_user_id_bcafa4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'app_key', 'view_key', 'name'), name='unique_filter_favorite_name_per_view'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'app_key', 'view_key'), name='unique_default_filter_favorite_per_view')],
            },
        ),
    ]
